#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
	paste -s -d '\n' <(networksetup -listallhardwareports | grep -A 1 "Ethernet$") <(ifconfig en0 | grep "inet[^6]" | cut -d " " -f 1,2)
else
	echo "0"
fi
